### ISSUE TITLE
Error while parsing time (futimes)

### ISSUE THREAD

**Issue by asgoth** [gulpjs/vinyl-fs#161]
All versions above 2.3.1 throw the following error:

    Error: Cannot parse time: 2016-02-29T15:22:45.000Z
      at toUnixTimestamp (fs.js:1056:9)
      at Object.fs.futimes (fs.js:1081:11)
      at times (/Users/louisdebevere/Development/git/repo/node_modules/vinyl-fs/lib/fileOperations.js:146:10)
      at onStat (/Users/louisdebevere/Development/git/repo/node_modules/vinyl-fs/lib/fileOperations.js:127:5)
      at FSReqWrap.oncomplete (fs.js:82:15)

On OSX 10.11.3

**Comment by phated** [comment]
Please supply a reproduction case because I have no idea how you are getting non-date objects

**Comment by asgoth** [comment]
I think it's an issue on my side. In some cases, we're sending (vinyl) files to a spawned process (using pipes on stdio) and receiving the result from it. The vinyl file gets corrupted when receiving it back from the spawned process.
