### ISSUE TITLE
Error: Cannot find module 'internal/fs'

### ISSUE THREAD

**Issue by FDiskas** [gulpjs/vinyl-fs#218]
Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/home/vytenis/***/front/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:11:1)

Node: 7
npm 4

**Comment by phated** [comment]
Don't use old vinyl-fs on node 7+. They broke shit.
