### ISSUE TITLE
Version 0.3.14: 8 tests failing run under Windows 10

### ISSUE THREAD

**Issue by BurtHarris** [gulpjs/vinyl-fs#264]
I thought I would look into backporting a fix for #262, so I did a checkout v0.3.14, built it and ran the tests.  Eight of them failed, is this expected?

```
C:\code\vinyl-fs>npm test

> vinyl-fs@0.3.14 test C:\code\vinyl-fs
> mocha --reporter spec && jshint lib

  dest stream
    √ should explode on invalid folder
    √ should pass through writes with cwd
    √ should pass through writes with default cwd
    √ should not write null files
    √ should write buffer files to the right folder with relative cwd
    √ should write buffer files to the right folder with function and relative cwd
    1) should write buffer files to the right folder
    2) should write streaming files to the right folder
    3) should write directories to the right folder
    √ should allow piping multiple dests in streaming mode
    √ should write new files with the default user mode
    4) should write new files with the specified mode
    5) should update file mode to match the vinyl mode
    6) should update directory mode to match the vinyl mode
    7) should report IO errors
    √ should report stat errors
    √ should report chmod errors
    8) should not chmod a matching file
    √ should emit end event
    √ should emit finish event

  source stream
    √ should explode on invalid glob (empty)
    √ should explode on invalid glob (number)
    √ should not explode on invalid glob (empty array)
    √ should pass through writes
    √ should strip BOM from UTF-8-encoded files
    √ should not strip anything that looks like a UTF-8-encoded BOM from UTF-16-BE-encoded files
    √ should not strip anything that looks like a UTF-8-encoded BOM from UTF-16-LE-encoded files
    √ should glob a file with default settings
    √ should glob a file with default settings and relative cwd
    √ should glob a directory with default settings
    √ should glob a file with with no contents
    √ should glob a file with streaming contents


  24 passing (318ms)
  8 failing

  1) dest stream should write buffer files to the right folder:

      Uncaught AssertionError: expected 438 to be 429
      + expected - actual

      -438
      +429

      at Proxy.fail (C:\code\vinyl-fs\node_modules\should\lib\assertion.js:228:17)
      at Proxy.prop.(anonymous function) (C:\code\vinyl-fs\node_modules\should\lib\assertion.js:69:14)
      at DestroyableTransform.onEnd [as _flush] (C:\code\vinyl-fs\test\dest.js:235:56)
      at DestroyableTransform.<anonymous> (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:135:12)
      at finishMaybe (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:371:12)
      at endWritable (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:378:3)
      at DestroyableTransform.Writable.end (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:356:5)
      at DestroyableTransform.onend (internal/streams/legacy.js:44:10)
      at C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)

  2) dest stream should write streaming files to the right folder:

      Uncaught AssertionError: expected 438 to be 429
      + expected - actual

      -438
      +429

      at Proxy.fail (C:\code\vinyl-fs\node_modules\should\lib\assertion.js:228:17)
      at Proxy.prop.(anonymous function) (C:\code\vinyl-fs\node_modules\should\lib\assertion.js:69:14)
      at DestroyableTransform.onEnd [as _flush] (C:\code\vinyl-fs\test\dest.js:276:56)
      at DestroyableTransform.<anonymous> (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:135:12)
      at finishMaybe (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:371:12)
      at endWritable (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:378:3)
      at DestroyableTransform.Writable.end (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:356:5)
      at DestroyableTransform.onend (internal/streams/legacy.js:44:10)
      at C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)

  3) dest stream should write directories to the right folder:

      Uncaught AssertionError: expected 438 to be 429
      + expected - actual

      -438
      +429

      at Proxy.fail (C:\code\vinyl-fs\node_modules\should\lib\assertion.js:228:17)
      at Proxy.prop.(anonymous function) (C:\code\vinyl-fs\node_modules\should\lib\assertion.js:69:14)
      at DestroyableTransform.onEnd [as _flush] (C:\code\vinyl-fs\test\dest.js:322:56)
      at DestroyableTransform.<anonymous> (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:135:12)
      at finishMaybe (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:371:12)
      at endWritable (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:378:3)
      at DestroyableTransform.Writable.end (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:356:5)
      at DestroyableTransform.onend (internal/streams/legacy.js:44:10)
      at C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)

  4) dest stream should write new files with the specified mode:

      Uncaught AssertionError: expected 438 to be 484
      + expected - actual

      -438
      +484

      at Proxy.fail (C:\code\vinyl-fs\node_modules\should\lib\assertion.js:228:17)
      at Proxy.prop.(anonymous function) (C:\code\vinyl-fs\node_modules\should\lib\assertion.js:69:14)
      at DestroyableTransform.onEnd [as _flush] (C:\code\vinyl-fs\test\dest.js:428:56)
      at DestroyableTransform.<anonymous> (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:135:12)
      at finishMaybe (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:371:12)
      at endWritable (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:378:3)
      at DestroyableTransform.Writable.end (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:356:5)
      at DestroyableTransform.onend (internal/streams/legacy.js:44:10)
      at C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)

  5) dest stream should update file mode to match the vinyl mode:

      Uncaught AssertionError: expected 438 to be 466
      + expected - actual

      -438
      +466

      at Proxy.fail (C:\code\vinyl-fs\node_modules\should\lib\assertion.js:228:17)
      at Proxy.prop.(anonymous function) (C:\code\vinyl-fs\node_modules\should\lib\assertion.js:69:14)
      at DestroyableTransform.onEnd [as _flush] (C:\code\vinyl-fs\test\dest.js:468:56)
      at DestroyableTransform.<anonymous> (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:135:12)
      at finishMaybe (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:371:12)
      at endWritable (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:378:3)
      at DestroyableTransform.Writable.end (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:356:5)
      at DestroyableTransform.onend (internal/streams/legacy.js:44:10)
      at C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)

  6) dest stream should update directory mode to match the vinyl mode:

      Uncaught AssertionError: expected 438 to be 471
      + expected - actual

      -438
      +471

      at Proxy.fail (C:\code\vinyl-fs\node_modules\should\lib\assertion.js:228:17)
      at Proxy.prop.(anonymous function) (C:\code\vinyl-fs\node_modules\should\lib\assertion.js:69:14)
      at DestroyableTransform.onEnd [as _flush] (C:\code\vinyl-fs\test\dest.js:513:56)
      at DestroyableTransform.<anonymous> (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:135:12)
      at finishMaybe (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:371:12)
      at endWritable (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:378:3)
      at DestroyableTransform.Writable.end (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:356:5)
      at DestroyableTransform.onend (internal/streams/legacy.js:44:10)
      at C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)

  7) dest stream should report IO errors:

      Uncaught AssertionError: expected 'EPERM' to be 'EACCES'
      + expected - actual

      -EPERM
      +EACCES

      at Proxy.fail (C:\code\vinyl-fs\node_modules\should\lib\assertion.js:228:17)
      at Proxy.prop.(anonymous function) (C:\code\vinyl-fs\node_modules\should\lib\assertion.js:69:14)
      at DestroyableTransform.<anonymous> (C:\code\vinyl-fs\test\dest.js:555:23)
      at onwriteError (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:250:10)
      at onwrite (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:268:5)
      at WritableState.onwrite (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:106:5)
      at afterTransform (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:104:5)
      at TransformState.afterTransform (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
      at done (C:\code\vinyl-fs\lib\dest\writeContents\index.js:11:7)
      at written (C:\code\vinyl-fs\lib\dest\writeContents\index.js:14:14)
      at fs.js:1319:7
      at OpenReq.Req.done (C:\code\vinyl-fs\node_modules\graceful-fs\graceful-fs.js:141:5)
      at OpenReq.done (C:\code\vinyl-fs\node_modules\graceful-fs\graceful-fs.js:61:22)
      at FSReqWrap.oncomplete (fs.js:123:15)

  8) dest stream should not chmod a matching file:
     Uncaught AssertionError: expected true not to be truthy
      at Assertion.fail (C:\code\vinyl-fs\node_modules\should\lib\assertion.js:228:17)
      at Assertion.prop.(anonymous function) [as ok] (C:\code\vinyl-fs\node_modules\should\lib\assertion.js:81:12)
      at Object.get (C:\code\vinyl-fs\node_modules\should\lib\assertion.js:258:26)
      at DestroyableTransform.onEnd [as _flush] (C:\code\vinyl-fs\test\dest.js:661:37)
      at DestroyableTransform.<anonymous> (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:135:12)
      at finishMaybe (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:371:12)
      at endWritable (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:378:3)
      at DestroyableTransform.Writable.end (C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:356:5)
      at DestroyableTransform.onend (internal/streams/legacy.js:44:10)
      at C:\code\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)

npm ERR! Test failed.  See above for more details.
```

Version info:
```
C:\code\vinyl-fs>node -v
v6.11.1

C:\code\vinyl-fs>npm -v
3.10.10

C:\code\vinyl-fs>git --version
git version 2.13.2.windows.1

C:\code\vinyl-fs>git describe
v0.3.14

```

**Comment by phated** [comment]
The old versions are hard-locked because the maintenance quality wasn't up to our current standards and I don't want to touch stuff that's "working" (in some sense of the word).
