### ISSUE TITLE
gulp build error 

### ISSUE THREAD

**Issue by nithya2609** [gulpjs/vinyl-fs#294]
Hi,
I get this below error.  can someone help?

[20:22:33] Error: Received a non-Vinyl object in `dest()`
    at DestroyableTransform.normalize [as _transform] (C:\Users\nspriya\clfa-tes                                                                                                                                  t-15jan\CLFA\node_modules\vinyl-fs\lib\dest\prepare.js:16:17)
    at DestroyableTransform.Transform._read (C:\Users\nspriya\clfa-test-15jan\CL                                                                                                                                  FA\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (C:\Users\nspriya\clfa-test-15jan\C                                                                                                                                  LFA\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readable-stre                                                                                                                                  am\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readabl                                                                                                                                  e-stream\lib\_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (C:\Users\nspriya\clfa-test-15jan\CLF                                                                                                                                  A\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at Pumpify.Duplexify._write (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modu                                                                                                                                  les\duplexify\index.js:212:22)
    at doWrite (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readable-stre                                                                                                                                  am\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readabl                                                                                                                                  e-stream\lib\_stream_writable.js:395:5)
    at Pumpify.Writable.write (C:\Users\nspriya\clfa-test-15jan\CLFA\node_module                                                                                                                                  s\readable-stream\lib\_stream_writable.js:322:11)
    at Transform.ondata (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\read                                                                                                                                  able-stream\lib\_stream_readable.js:612:20)
    at emitOne (events.js:96:13)
    at Transform.emit (events.js:188:7)
    at addChunk (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readable-str                                                                                                                                  eam\lib\_stream_readable.js:284:12)
    at readableAddChunk (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\read                                                                                                                                  able-stream\lib\_stream_readable.js:271:11)
    at Transform.Readable.push (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modul                                                                                                                                  es\readable-stream\lib\_stream_readable.js:238:10)
    at Transform.push (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readab                                                                                                                                  le-stream\lib\_stream_transform.js:146:32)
    at C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\gulp-htmlmin\index.js:                                                                                                                                  56:16
    at C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\gulp-htmlmin\index.js:                                                                                                                                  29:11
    at module.exports (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\tryit\                                                                                                                                  tryit.js:13:13)
    at minifyHtml (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\gulp-htmlm                                                                                                                                  in\index.js:21:9)
    at Transform.htmlminTransform [as _transform] (C:\Users\nspriya\clfa-test-15                                                                                                                                  jan\CLFA\node_modules\gulp-htmlmin\index.js:51:7)
    at Transform._read (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\reada                                                                                                                                  ble-stream\lib\_stream_transform.js:182:10)
    at Transform._write (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\read                                                                                                                                  able-stream\lib\_stream_transform.js:170:83)
    at doWrite (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readable-stre                                                                                                                                  am\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readabl                                                                                                                                  e-stream\lib\_stream_writable.js:395:5)
    at Transform.Writable.write (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modu                                                                                                                                  les\readable-stream\lib\_stream_writable.js:322:11)
    at DestroyableTransform.ondata (C:\Users\nspriya\clfa-test-15jan\CLFA\node_m                                                                                                                                  odules\readable-stream\lib\_stream_readable.js:612:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at addChunk (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readable-str                                                                                                                                  eam\lib\_stream_readable.js:284:12)
    at readableAddChunk (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\read                                                                                                                                  able-stream\lib\_stream_readable.js:271:11)
    at DestroyableTransform.Readable.push (C:\Users\nspriya\clfa-test-15jan\CLFA                                                                                                                                  \node_modules\readable-stream\lib\_stream_readable.js:238:10)
    at DestroyableTransform.Transform.push (C:\Users\nspriya\clfa-test-15jan\CLF                                                                                                                                  A\node_modules\readable-stream\lib\_stream_transform.js:146:32)
    at afterTransform (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readab                                                                                                                                  le-stream\lib\_stream_transform.js:102:51)
    at TransformState.afterTransform (C:\Users\nspriya\clfa-test-15jan\CLFA\node                                                                                                                                  _modules\readable-stream\lib\_stream_transform.js:79:12)
    at DestroyableTransform.minify [as _transform] (C:\Users\nspriya\clfa-test-1                                                                                                                                  5jan\CLFA\node_modules\gulp-minify-inline\index.js:73:3)
    at DestroyableTransform.Transform._read (C:\Users\nspriya\clfa-test-15jan\CL                                                                                                                                  FA\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (C:\Users\nspriya\clfa-test-15jan\C                                                                                                                                  LFA\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readable-stre                                                                                                                                  am\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readabl                                                                                                                                  e-stream\lib\_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (C:\Users\nspriya\clfa-test-15jan\CLF                                                                                                                                  A\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at Stream.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at queueData (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\map-stream\                                                                                                                                  index.js:43:21)
    at next (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\map-stream\index                                                                                                                                  .js:71:7)
    at C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\map-stream\index.js:85                                                                                                                                  :7
    at C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\spock\index.js:38:5
    at wrappedMapper (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\map-str                                                                                                                                  eam\index.js:84:19)
    at Stream.stream.write (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\m                                                                                                                                  ap-stream\index.js:96:21)
    at DestroyableTransform.ondata (C:\Users\nspriya\clfa-test-15jan\CLFA\node_m                                                                                                                                  odules\readable-stream\lib\_stream_readable.js:612:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at addChunk (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readable-str                                                                                                                                  eam\lib\_stream_readable.js:284:12)
    at readableAddChunk (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\read                                                                                                                                  able-stream\lib\_stream_readable.js:271:11)
    at DestroyableTransform.Readable.push (C:\Users\nspriya\clfa-test-15jan\CLFA                                                                                                                                  \node_modules\readable-stream\lib\_stream_readable.js:238:10)
    at DestroyableTransform.Transform.push (C:\Users\nspriya\clfa-test-15jan\CLF                                                                                                                                  A\node_modules\readable-stream\lib\_stream_transform.js:146:32)
    at Pumpify.onReadable (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\to                                                                                                                                  -through\index.js:25:14)
    at emitNone (events.js:86:13)
    at Pumpify.emit (events.js:185:7)
    at emitReadable_ (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readabl                                                                                                                                  e-stream\lib\_stream_readable.js:497:10)
    at emitReadable (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readable                                                                                                                                  -stream\lib\_stream_readable.js:491:65)
    at addChunk (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readable-str                                                                                                                                  eam\lib\_stream_readable.js:291:29)
    at readableAddChunk (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\read                                                                                                                                  able-stream\lib\_stream_readable.js:271:11)
    at Pumpify.Readable.push (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules                                                                                                                                  \readable-stream\lib\_stream_readable.js:238:10)
    at Pumpify.Duplexify._forward (C:\Users\nspriya\clfa-test-15jan\CLFA\node_mo                                                                                                                                  dules\duplexify\index.js:165:26)
    at DestroyableTransform.onreadable (C:\Users\nspriya\clfa-test-15jan\CLFA\no                                                                                                                                  de_modules\duplexify\index.js:129:10)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at emitReadable_ (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readabl                                                                                                                                  e-stream\lib\_stream_readable.js:497:10)
    at emitReadable (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readable                                                                                                                                  -stream\lib\_stream_readable.js:491:65)
    at addChunk (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readable-str                                                                                                                                  eam\lib\_stream_readable.js:291:29)
    at readableAddChunk (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\read                                                                                                                                  able-stream\lib\_stream_readable.js:271:11)
    at DestroyableTransform.Readable.push (C:\Users\nspriya\clfa-test-15jan\CLFA                                                                                                                                  \node_modules\readable-stream\lib\_stream_readable.js:238:10)
    at DestroyableTransform.Transform.push (C:\Users\nspriya\clfa-test-15jan\CLF                                                                                                                                  A\node_modules\readable-stream\lib\_stream_transform.js:146:32)
    at afterTransform (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readab                                                                                                                                  le-stream\lib\_stream_transform.js:102:51)
    at TransformState.afterTransform (C:\Users\nspriya\clfa-test-15jan\CLFA\node                                                                                                                                  _modules\readable-stream\lib\_stream_transform.js:79:12)
    at DestroyableTransform.addSourcemap [as _transform] (C:\Users\nspriya\clfa-                                                                                                                                  test-15jan\CLFA\node_modules\vinyl-fs\lib\src\sourcemap.js:12:14)
    at DestroyableTransform.Transform._read (C:\Users\nspriya\clfa-test-15jan\CL                                                                                                                                  FA\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (C:\Users\nspriya\clfa-test-15jan\C                                                                                                                                  LFA\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readable-stre                                                                                                                                  am\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readabl                                                                                                                                  e-stream\lib\_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (C:\Users\nspriya\clfa-test-15jan\CLF                                                                                                                                  A\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at DestroyableTransform.ondata (C:\Users\nspriya\clfa-test-15jan\CLFA\node_m                                                                                                                                  odules\readable-stream\lib\_stream_readable.js:612:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at addChunk (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readable-str                                                                                                                                  eam\lib\_stream_readable.js:284:12)
    at readableAddChunk (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\read                                                                                                                                  able-stream\lib\_stream_readable.js:271:11)
    at DestroyableTransform.Readable.push (C:\Users\nspriya\clfa-test-15jan\CLFA                                                                                                                                  \node_modules\readable-stream\lib\_stream_readable.js:238:10)
    at DestroyableTransform.Transform.push (C:\Users\nspriya\clfa-test-15jan\CLF                                                                                                                                  A\node_modules\readable-stream\lib\_stream_transform.js:146:32)
    at afterTransform (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\readab                                                                                                                                  le-stream\lib\_stream_transform.js:102:51)
    at TransformState.afterTransform (C:\Users\nspriya\clfa-test-15jan\CLFA\node                                                                                                                                  _modules\readable-stream\lib\_stream_transform.js:79:12)
    at onRead (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\vinyl-fs\lib\s                                                                                                                                  rc\read-contents\index.js:45:14)
    at onReadFile (C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\vinyl-fs\l                                                                                                                                  ib\src\read-contents\read-buffer.js:21:5)
    at C:\Users\nspriya\clfa-test-15jan\CLFA\node_modules\graceful-fs\graceful-f                                                                                                                                  s.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)

[20:22:33] 'build:dist' errored after 8.37 s
[20:22:33] 'build' errored after 8.37 s
[20:22:33] The following tasks did not complete: moveHtml, move404Html, moveBowe                                                                                                                                  rComponentImagesToDist, moveImagesToDist, moveFontsToDist, moveIconsToDist, move                                                                                                                                  JsonToDist, moveServerConfigFiles, moveScriptsToDist, moveCssToDist, moveAndTemp

**Comment by phated** [comment]
Looks like you are using an old version `gulp-htmlmin` - have you tried running `npm outdated` recently?

**Comment by nithya2609** [comment]
Hi,
Thanks for the reply.is there a way i can install gulp local 4.0.0 alpha 2 and not 3>?

**Comment by nithya2609** [comment]
$ npm outdated
Package                              Current   Wanted  Latest  Location
chai                                   3.5.0    3.5.0   4.1.2  clfatest
chalk                                  1.1.3    1.1.3   2.3.0  clfatest
del                                    2.2.2    2.2.2   3.0.0  clfatest
eslint                                2.13.1   2.13.1  4.15.0  clfatest
eslint-html-reporter                  0.4.14   0.4.14   0.5.2  clfatest
eslint-plugin-angular                  1.0.0    1.0.0   3.1.1  clfatest
globby                                 4.1.0    4.1.0   7.1.1  clfatest
gulp                           4.0.0-alpha.3      git     git  clfatest
gulp-angular-templatecache             1.9.1    1.9.1   2.2.0  clfatest
gulp-autoprefixer                      3.1.1    3.1.1   4.1.0  clfatest
gulp-bump                              2.9.0    2.9.0   3.0.0  clfatest
gulp-eslint                            2.1.0    2.1.0   4.0.1  clfatest
gulp-flatten                           0.2.0    0.2.0   0.4.0  clfatest
gulp-git                              1.15.1   1.15.1   2.5.0  clfatest
gulp-htmlmin                           2.0.0    2.0.0   4.0.0  clfatest
gulp-minify-inline                     0.2.1    0.2.1   1.0.0  clfatest
gulp-replace                           0.5.4    0.5.4   0.6.1  clfatest
gulp-rev                               7.1.2    7.1.2   8.1.1  clfatest
gulp-sass                              2.3.2    2.3.2   3.1.0  clfatest
gulp-size                              2.1.0    2.1.0   3.0.0  clfatest
gulp-sourcemaps                       1.12.0   1.12.0   2.6.3  clfatest
gulp-uglify                            1.5.4    1.5.4   3.0.0  clfatest
gulp-watch                            4.3.11   4.3.11   5.0.0  clfatest
icap-publish                           1.1.0      git     git  clfatest
karma                                0.13.22  0.13.22   2.0.0  clfatest
karma-chrome-launcher                  0.2.3    0.2.3   2.2.0  clfatest
karma-coffee-preprocessor              0.3.0    0.3.0   1.0.1  clfatest
karma-coverage                         0.5.5    0.5.5   1.1.1  clfatest
karma-firefox-launcher                 0.1.7    0.1.7   1.1.0  clfatest
karma-ie-launcher                      0.2.0    0.2.0   1.0.0  clfatest
karma-mocha                            0.2.2    0.2.2   1.3.0  clfatest
karma-ng-html2js-preprocessor          0.2.2    0.2.2   1.0.0  clfatest
karma-ng-scenario                      0.1.0    0.1.0   1.0.0  clfatest
lodash                                3.10.1   3.10.1  4.17.4  clfatest
mocha                                  2.5.3    2.5.3   4.1.0  clfatest
sinon                                 1.17.7   1.17.7   4.1.5  clfatest
yargs                                  4.8.1    4.8.1  10.1.1  clfatest

**Comment by nithya2609** [comment]
Thanks for the reply.is there a way i can install gulp local 4.0.0 alpha 2 and not 3>?

**Comment by phated** [comment]
@nithya2609 we aren't here to be your personal support forum.  Support questions should be directed to StackOverflow.
