### ISSUE TITLE
Cannot find module 'natives'

### ISSUE THREAD

**Issue by FSElias** [gulpjs/vinyl-fs#297]
Hello,
after installing gulp, when I run it I get the error:
module.js:549
    throw err;
    ^

Error: Cannot find module 'natives'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (XXXXXXXX\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:80)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by phated** [comment]
The version of vinyl-fs that's published as latest does not use graceful-fs which relies on natives.  You are likely getting this by installing gulp 3.x on a newer node where they decided to break shit.  Don't do that.  You'll likely have to downgrade node or upgrade to gulp 4 (`npm install gulp@next`).

**Comment by contra** [comment]
This should be fixed by running `npm update` - btw. When you update node theres an underlying shim module that needs to be updated as well.
