### ISSUE TITLE
graceful-fs / natives issue broken with node v10+

### ISSUE THREAD

**Issue by brandonros** [gulpjs/vinyl-fs#309]
```
$ gulp
internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/Users/bros/repos/redacted/projects/redacted/node_modules/vinyl-fs/node_modules/natives/index.js:140:5)
    at require (/Users/bros/repos/redacted/projects/redacted/node_modules/vinyl-fs/node_modules/natives/index.js:113:12)
    at util.js:25:21
    at req_ (/Users/bros/repos/redacted/projects/redacted/node_modules/vinyl-fs/node_modules/natives/index.js:140:5)
    at require (/Users/bros/repos/redacted/projects/redacted/node_modules/vinyl-fs/node_modules/natives/index.js:113:12)
    at fs.js:42:21
    at req_ (/Users/bros/repos/redacted/projects/redacted/node_modules/vinyl-fs/node_modules/natives/index.js:140:5)
    at Object.req [as require] (/Users/bros/repos/redacted/projects/redacted/node_modules/vinyl-fs/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/Users/bros/repos/redacted/projects/redacted/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:99)
```

```
$ node -v
v10.15.0
```

`cd node_modules/vinyl-fs && yarn add natives@1.1.16` fixes the issue but I'm not sure if that should be fixed here or graceful-fs? 

```
$ npm ls vinyl-fs
@banno/redacted@1.843.0 /Users/bros/repos/redacted/projects/redacted
├─┬ @banno/whitesource@1.0.7
│ └─┬ download@4.4.3
│   ├─┬ gulp-decompress@1.2.0
│   │ └─┬ decompress@3.0.0
│   │   └── vinyl-fs@2.4.4
│   └── vinyl-fs@2.4.4
├─┬ gulp@3.9.1
│ └── vinyl-fs@0.3.14
└─┬ gulp-add-src@0.2.0
  └── vinyl-fs@0.3.14  deduped
```

**Comment by phated** [comment]
Neither, you just needed to update your yarn file...

**Comment by brandonros** [comment]
> Neither, you just needed to update your yarn file...

Can you elaborate on this?...

**Comment by phated** [comment]
The natives package, like you did.  It was backported into graceful-fs through the use of semver.  Lockfiles are antithetical to semver so you hadn't received the fix.

Gulp 3.x is very old.  Gulp 4 was published as latest in December after a full year of public release as the `next` tag.
